# Generated by Django 4.0.2 on 2022-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contact_delete_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
