# Generated by Django 4.0.2 on 2022-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='signature',
        ),
        migrations.AddField(
            model_name='signature',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
