# Generated by Django 4.0.1 on 2022-02-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPlaceHolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_holder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailMapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
                ('is_starred', models.BooleanField()),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emails.email')),
                ('place_holder_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emails.emailplaceholders')),
            ],
        ),
    ]
