# Generated by Django 4.0.2 on 2022-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='useremailmapped',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='useremailmapped',
            old_name='place_holder_id',
            new_name='place_holder',
        ),
        migrations.RenameField(
            model_name='useremailmapped',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
