# Generated by Django 4.0.2 on 2022-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_rename_author_id_email_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.AddField(
            model_name='useremailmapped',
            name='bcc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useremailmapped',
            name='cc',
            field=models.BooleanField(default=False),
        ),
    ]
