# Generated by Django 4.0.2 on 2022-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_email_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailmapped',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='useremailmapped',
            name='cc',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
