# Generated by Django 4.0.2 on 2022-03-04 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emails.models
import emails.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0014_email_reply_alter_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailplaceholders',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=emails.models.user_directory_path, validators=[emails.validators.validate_file_size]),
        ),
    ]
