# Generated by Django 4.0.2 on 2022-03-10 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0015_emailplaceholders_creator_alter_email_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(blank=True, related_name='bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='email',
            name='to',
        ),
        migrations.AddField(
            model_name='email',
            name='to',
            field=models.ManyToManyField(blank=True, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
    ]
