# Generated by Django 4.0.2 on 2022-03-10 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0016_remove_email_bcc_email_bcc_remove_email_cc_email_cc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to',
        ),
        migrations.CreateModel(
            name='EmailReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcc', models.ManyToManyField(blank=True, related_name='bcc', to=settings.AUTH_USER_MODEL)),
                ('cc', models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to', models.ManyToManyField(blank=True, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
