# Generated by Django 4.0.2 on 2022-03-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_remove_email_bcc_remove_email_cc_remove_email_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreceiver',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email'),
        ),
    ]
