# Generated by Django 4.0.2 on 2022-03-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_alter_emailplaceholders_place_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emails.email')),
                ('place_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emails.emailplaceholders')),
            ],
        ),
    ]
