# Generated by Django 4.0.2 on 2022-03-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0020_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emails.email'),
        ),
    ]
