# Generated by Django 4.0.2 on 2022-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0022_filter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
