# Generated by Django 4.0.2 on 2022-03-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0024_alter_filter_sender_alter_filter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailmapped',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email'),
        ),
        migrations.AlterField(
            model_name='useremailmapped',
            name='place_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailplaceholders'),
        ),
        migrations.AlterField(
            model_name='useremailmapped',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
