# Generated by Django 4.0.2 on 2022-03-28 18:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0027_email_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
